[program:emulator]
command=bash -c 'sleep 5 && /opt/android-sdk/emulator/emulator -avd custom_rom_avd -no-window -no-audio -writable-system -qemu -enable-kvm'
autostart=true
autorestart=true
stderr_logfile=/var/log/emulator/emulator.log
stdout_logfile=/var/log/emulator/emulator.log
priority=300
environment=DISPLAY=:99,ANDROID_SDK_ROOT=/opt/android-sdk
startsecs=10