[program:novnc]
command=bash -c 'sleep 10 && websockify --web=/usr/share/novnc 6080 localhost:5900'
autostart=true
autorestart=true
stderr_logfile=/var/log/emulator/novnc.log
stdout_logfile=/var/log/emulator/novnc.log
priority=250