[program:vnc]
command=/usr/bin/x11vnc -display :99 -forever -nopw -listen 0.0.0.0 -rfbport 5900
autostart=true
autorestart=true
stderr_logfile=/var/log/emulator/vnc.log
stdout_logfile=/var/log/emulator/vnc.log
priority=200
environment=DISPLAY=:99